version: "3.9"

services:
  unbank_db:
    image: postgres:12
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"    
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aleo62

  unbank_api:
    depends_on:
      - unbank_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://unbank_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - aleo62

volumes:
  pgdata: {}

networks:
  aleo62:
    driver: bridge